language: c
os: linux
services:
    - docker
before_install:
    - sudo apt-get -y install meson
    - sudo apt-get -y install julia
script:
    - meson build
    - cd meson
    - meson compile
    - meson install
