language: c
os: linux
dist: focal
services:
    - docker
before_install:
    - sudo apt-get -y install meson
    - sudo apt-get -y install libwayland-dev
    - sudo apt-get -y install julia
    - sudo apt-get -y install libwlroots-dev
script:
    - mkdir build
    - meson build
    - cd build
    - meson compile
    - meson install
