language: c
os: linux
dist: focal
services:
    - docker
before_install:
    - pip3 install meson
    - sudo apt-get -y install libwayland-dev
    - sudo apt-get -y install wayland-protocols
    - sudo apt-get -y install libjulia-dev
    - git clone "https://github.com/swaywm/wlroots"
    - cd wlroots
    - meson build
    - ninja -C build
    - cd build
    - sudo meson install
    - cd ../../
script:
    - mkdir build
    - meson build
    - cd build
    - meson compile
    - meson install
