os: linux
dist: focal
services:
- docker

archlinux:
  before_install:
  script:
  - "echo works"

before_install:
    - docker pull archlinux
    - docker run -it --rm arch archlinux
    - docker exec build git clone "https://github.com/werererer/juliawm"
    - docker exec cd juliawm
    - docker exec arch sudo pacman -S --noconfirm wlroots
    - docker exec arch sudo pacman -S --noconfirm julia
    - docker exec arch sudo pacman -S --noconfirm wayland
    - docker exec arch sudo pacman -S --noconfirm meson
script:
    - docker exec arch meson build
    - docker exec arch cd build
    - docker exec arch meson compile
    - docker exec arch meson install
