name = "juliawm"
uuid = "693f1b80-3e1a-4659-9766-75ba891126f4"
authors = ["Jakob Schlanstedt <johann123j@gmail.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
