version: 2.1
docker:
    - image: archlinux
updatepackage:
    name: Update Packages
    command: sudo pacman -Syu --noconfirm
jobs:
    one:
        docker:
            - image: archlinux
        steps:
            - run: pacman -Sy --noconfirm
            - run: pacman -S --noconfirm base-devel
            - run: pacman -S --noconfirm meson
            - run: pacman -S --noconfirm wlroots
            - run: pacman -S --noconfirm julia
            - run: pacman -S --noconfirm cairo
            - run: pacman -S --noconfirm wayland
            - run: pacman -S --noconfirm wayland-protocols
            - run: pacman -S --noconfirm cmocka
            - run: pacman -S --noconfirm gcovr
            - checkout
            - run: ls
            - run: meson -Db_coverage=true build
            - run: cd build && meson compile
            - run: cd build && meson test
            - run: ninja -C build coverage
            - run: bash <(curl -s https://codecov.io/bash)
workflows:
    one:
        jobs:
            - one
