version: 2.1
jobs:
    one:
        docker:
            - image: archlinux
        steps:
            - checkout
            - run: pacman -Sy --noconfirm
            - run: pacman -S --noconfirm base-devel
            - run: pacman -S --noconfirm meson
            - run: pacman -S --noconfirm wlroots
            - run: pacman -S --noconfirm lua
            - run: pacman -S --noconfirm wayland
            - run: pacman -S --noconfirm wayland-protocols
            - run: pacman -S --noconfirm check
            - run: pacman -S --noconfirm gcovr
            - run: ls
            - run: whereis gcc
            - run: meson -Db_coverage=true build
            - run: cat /root/project/build/meson-logs/meson-log.txt
            - run: cd build && meson compile
            - run: cd build && meson test
            - store_test_results:
                path: build/meson-logs
            - run: ninja -C build coverage
            - run: bash <(curl -s https://codecov.io/bash)
workflows:
    one:
        jobs:
            - one
