# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
docker:
    - image: archlinux
updatepackage:
    name: Update Packages
    command: sudo pacman -Syu --noconfirm
jobs:
    one:
        docker:
            - image: archlinux
        steps:
            - checkout
            - run: echo "works"
            - run: sleep 15
workflows:
    one:
        jobs:
            - one
