name: Tests
on:
  push:
      branches:
          - master
          - development
  workflow_dispatch:
jobs:
    container:
        runs-on: ubuntu-latest
        container: archlinux
        steps:
            - uses: actions/checkout@v2
            - run: |
                uname -a
                pacman -Sy --noconfirm
                pacman -S --noconfirm base-devel
                pacman -S --noconfirm git
                git clone https://aur.archlinux.org/paru.git
                cd paru
                makepkg -si
                paru -S japokwm-git
              name: Run Test Aur
