name: Tests
on:
  push:
      branches:
          - master
          - development
  workflow_dispatch:
jobs:
    container:
        runs-on: ubuntu-latest
        container: archlinux
        steps:
            - uses: actions/checkout@v2
            - run: |
                uname -a
                pacman -Sy --noconfirm
                pacman -S --noconfirm base-devel
                pacman -S --noconfirm glib2
                pacman -S --noconfirm libuv
                pacman -S --noconfirm meson
                pacman -S --noconfirm wlroots
                pacman -S --noconfirm lua
                pacman -S --noconfirm wayland
                pacman -S --noconfirm wayland-protocols
                pacman -S --noconfirm libnotify
                pacman -S --noconfirm scdoc
              name: Run in container
            - run: |
                meson -Db_coverage=true build
                meson compile -C build
                meson test -C build
              name: Build
            # - run: |
            #     ninja coverage -C build
            #     bash <(curl -s https://codecov.io/bash)
            #   name: Upload coverage
            - name: Publish Unit Test Results
              uses: EnricoMi/publish-unit-test-result-action@v1
              if: always()
              with:
                  files: build/meson-logs/*.xml
